#index:
#    path: /
#    controller: App\Controller\DefaultController::index
rycerz:
   path: /rycerz
   controller: App\Controller\KnightController::attack
lucznik:
   path: /lucznik
   controller: App\Controller\ArcherController::attack
wojownik:
   path: /wojownik
   controller: App\Controller\WarriorController::attack
share:
   path: /share
   controller: App\Controller\SocialMediaController::share
pizza:
   path: /pizza
   controller: App\Controller\PizzaController::plain
chicken:
   path: /pizza/chicken
   controller: App\Controller\PizzaController::chicken
salami:
   path: /pizza/salami
   controller: App\Controller\PizzaController::salami